# Generated by Django 4.0.6 on 2022-09-30 15:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(default=datetime.datetime(2022, 9, 30, 17, 37, 54, 658601))),
                ('permission', models.CharField(choices=[(1, 'Owner'), (2, 'Admin'), (3, 'Writer'), (4, 'Reader')], default=4, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2022, 9, 30, 17, 37, 54, 657601))),
                ('anonymous_clients', models.ManyToManyField(related_name='boards', through='main.AnonymousParticipation', to='main.anonymousclient')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(default=datetime.datetime(2022, 9, 30, 17, 37, 54, 658601))),
                ('permission', models.CharField(choices=[(1, 'Owner'), (2, 'Admin'), (3, 'Writer'), (4, 'Reader')], default=4, max_length=64)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.board')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
            ],
            options={
                'unique_together': {('client', 'board')},
            },
        ),
        migrations.AddField(
            model_name='board',
            name='clients',
            field=models.ManyToManyField(related_name='boards', through='main.UserParticipation', to='main.client'),
        ),
        migrations.CreateModel(
            name='AuthenticationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_link', to='main.board')),
            ],
        ),
        migrations.AddField(
            model_name='anonymousparticipation',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.board'),
        ),
        migrations.AddField(
            model_name='anonymousparticipation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.anonymousclient'),
        ),
        migrations.AlterUniqueTogether(
            name='anonymousparticipation',
            unique_together={('client', 'board')},
        ),
    ]
