# Generated by Django 4.0.6 on 2022-09-30 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousparticipation',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 17, 37, 58, 849037)),
        ),
        migrations.AlterField(
            model_name='board',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 17, 37, 58, 848036)),
        ),
        migrations.AlterField(
            model_name='userparticipation',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 17, 37, 58, 849037)),
        ),
    ]
