# Generated by Django 4.0.6 on 2022-09-30 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_anonymousparticipation_join_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousparticipation',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 17, 58, 9, 535656)),
        ),
        migrations.AlterField(
            model_name='anonymousparticipation',
            name='permission',
            field=models.IntegerField(choices=[(1, 'Owner'), (2, 'Admin'), (3, 'Writer'), (4, 'Reader')], default=4),
        ),
        migrations.AlterField(
            model_name='board',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 17, 58, 9, 534655)),
        ),
        migrations.AlterField(
            model_name='userparticipation',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 17, 58, 9, 535656)),
        ),
        migrations.AlterField(
            model_name='userparticipation',
            name='permission',
            field=models.IntegerField(choices=[(1, 'Owner'), (2, 'Admin'), (3, 'Writer'), (4, 'Reader')], default=4),
        ),
    ]
