# Generated by Django 4.0.6 on 2022-10-05 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_anonymousparticipation_join_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousparticipation',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 18, 17, 16, 13240)),
        ),
        migrations.AlterField(
            model_name='board',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 18, 17, 16, 13240)),
        ),
        migrations.AlterField(
            model_name='userparticipation',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 18, 17, 16, 13240)),
        ),
    ]
