# Generated by Django 4.0.6 on 2022-10-05 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_anonymousparticipation_join_date_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='anonymousparticipation',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 0, 20, 16, 834766)),
        ),
        migrations.AlterField(
            model_name='board',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 0, 20, 16, 833765)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userparticipation',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 0, 20, 16, 834766)),
        ),
    ]
